server:
  port: 8089
  servlet:
    context-path: /demo

spring:
  data:
    redis:
      # 您的本机 Redis 地址
      host: localhost
      port: 6379
      # 如果您的 Redis 有密码，请在这里填入
      password: "" 
      # 连接池配置
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
